// THIS FILE IS AUTOGENERATED using 'yarn typegen'. DO NOT EDIT IT DIRECTLY!
import type {
  OpenAPIClient,
  Parameters,
  UnknownParamsObject,
  OperationResponse,
  AxiosRequestConfig,
} from 'openapi-client-axios'; 

declare namespace Components {
    namespace Schemas {
        /**
         * Article
         *
         * example:
         */
        export interface Article {
            /**
             * Unique identifier for the given user.
             */
            id: number;
            title: string;
            imageUrl: string;
            content: string;
            author: string;
            /**
             * Set to true if the user's email has been verified.
             */
            updatedAt: number;
            createdAt: number;
        }
    }
}
declare namespace Paths {
    namespace Article$Id {
        namespace Parameters {
            export type Id = string;
        }
        export interface PathParameters {
            id: Parameters.Id;
        }
    }
    namespace DeleteArticle {
        namespace Parameters {
            export type Id = string;
        }
        export interface PathParameters {
            id: Parameters.Id;
        }
        namespace Responses {
            export interface $204 {
            }
        }
    }
    namespace GetArticle {
        namespace Parameters {
            export type Id = string;
        }
        export interface PathParameters {
            id: Parameters.Id;
        }
        namespace Responses {
            export type $200 = /**
             * Article
             *
             * example:
             */
            Components.Schemas.Article;
        }
    }
    namespace ListArticle {
        namespace Responses {
            export interface $200 {
                total?: number;
                results?: /**
                 * Article
                 *
                 * example:
                 */
                Components.Schemas.Article[];
            }
        }
    }
    namespace PatchArticle {
        namespace Parameters {
            export type Id = string;
        }
        export interface PathParameters {
            id: Parameters.Id;
        }
        export type RequestBody = /**
         * Article
         *
         * example:
         */
        Components.Schemas.Article;
        namespace Responses {
            export type $200 = /**
             * Article
             *
             * example:
             */
            Components.Schemas.Article;
        }
    }
    namespace PostArticle {
        export type RequestBody = /**
         * Article
         *
         * example:
         */
        Components.Schemas.Article;
        namespace Responses {
            export type $201 = /**
             * Article
             *
             * example:
             */
            Components.Schemas.Article;
        }
    }
}

export interface OperationMethods {
  /**
   * getArticle - Update an article
   */
  'getArticle'(
    parameters?: Parameters<Paths.GetArticle.PathParameters> | null,
    data?: any,
    config?: AxiosRequestConfig  
  ): OperationResponse<Paths.GetArticle.Responses.$200>
  /**
   * patchArticle - Update an article
   */
  'patchArticle'(
    parameters?: Parameters<Paths.PatchArticle.PathParameters> | null,
    data?: Paths.PatchArticle.RequestBody,
    config?: AxiosRequestConfig  
  ): OperationResponse<Paths.PatchArticle.Responses.$200>
  /**
   * deleteArticle - Delete an article
   */
  'deleteArticle'(
    parameters?: Parameters<Paths.DeleteArticle.PathParameters> | null,
    data?: any,
    config?: AxiosRequestConfig  
  ): OperationResponse<Paths.DeleteArticle.Responses.$204>
  /**
   * listArticle - List articles
   */
  'listArticle'(
    parameters?: Parameters<UnknownParamsObject> | null,
    data?: any,
    config?: AxiosRequestConfig  
  ): OperationResponse<Paths.ListArticle.Responses.$200>
  /**
   * postArticle - Create an article
   */
  'postArticle'(
    parameters?: Parameters<UnknownParamsObject> | null,
    data?: Paths.PostArticle.RequestBody,
    config?: AxiosRequestConfig  
  ): OperationResponse<Paths.PostArticle.Responses.$201>
}

export interface PathsDictionary {
  ['/article/{id}']: {
    /**
     * getArticle - Update an article
     */
    'get'(
      parameters?: Parameters<Paths.GetArticle.PathParameters> | null,
      data?: any,
      config?: AxiosRequestConfig  
    ): OperationResponse<Paths.GetArticle.Responses.$200>
    /**
     * patchArticle - Update an article
     */
    'patch'(
      parameters?: Parameters<Paths.PatchArticle.PathParameters> | null,
      data?: Paths.PatchArticle.RequestBody,
      config?: AxiosRequestConfig  
    ): OperationResponse<Paths.PatchArticle.Responses.$200>
    /**
     * deleteArticle - Delete an article
     */
    'delete'(
      parameters?: Parameters<Paths.DeleteArticle.PathParameters> | null,
      data?: any,
      config?: AxiosRequestConfig  
    ): OperationResponse<Paths.DeleteArticle.Responses.$204>
  }
  ['/article']: {
    /**
     * listArticle - List articles
     */
    'get'(
      parameters?: Parameters<UnknownParamsObject> | null,
      data?: any,
      config?: AxiosRequestConfig  
    ): OperationResponse<Paths.ListArticle.Responses.$200>
    /**
     * postArticle - Create an article
     */
    'post'(
      parameters?: Parameters<UnknownParamsObject> | null,
      data?: Paths.PostArticle.RequestBody,
      config?: AxiosRequestConfig  
    ): OperationResponse<Paths.PostArticle.Responses.$201>
  }
}

export type Client = OpenAPIClient<OperationMethods, PathsDictionary>
